## Example of diagonalization of a symmetric matrix
Plus the result of multiplying $T_k = XV_k$

In [14]:
import numpy as np
A = np.random.randint(10,size=(3,3))
A

array([[2, 0, 3],
       [9, 1, 6],
       [8, 3, 6]])

In [15]:
Sigma = A.T*A #Always a symmetric matrix

In [16]:
Sigma

array([[ 4,  0, 24],
       [ 0,  1, 18],
       [24, 18, 36]])

In [20]:
eig_val, eig_vec = np.linalg.eigh(Sigma)

In [21]:
eig_val

array([-14.88807747,   2.16025946,  53.72781801])

In [22]:
V = eig_vec
V

array([[ 0.64357573,  0.64280791, -0.4154615 ],
       [ 0.57382218, -0.76444095, -0.29386756],
       [-0.50649618, -0.04927499, -0.86083308]])

In [23]:
Lambda = np.diag(eig_val)
Lambda

array([[-14.88807747,   0.        ,   0.        ],
       [  0.        ,   2.16025946,   0.        ],
       [  0.        ,   0.        ,  53.72781801]])

In [35]:
Verify = V@Lambda@V.T #when the orignal matrix is symmetric, this implies V is orthogonal and V.T equals V inverse.
np.round(Verify)

array([[ 4., -0., 24.],
       [-0.,  1., 18.],
       [24., 18., 36.]])

In [40]:
k = 2
Vk = V[:,:k]
Vk

array([[ 0.64357573,  0.64280791],
       [ 0.57382218, -0.76444095],
       [-0.50649618, -0.04927499]])

In [43]:
Verify2 = V.T@Sigma@V #returns eigenvalues
np.round(Verify2)

array([[-15.,  -0.,  -0.],
       [ -0.,   2.,  -0.],
       [  0.,  -0.,  54.]])

In [46]:
Verify3 = Vk.T@Sigma@Vk #only returns first k eigenvalues
np.round(Verify3)

array([[-15.,  -0.],
       [ -0.,   2.]])